import { describe, expect, it } from 'vitest'
import { ExecutionCoordinator } from './executionCoordinator'

const scope = { requestId: 'one', task: 'chat' as const, ownerId: 1, documentId: 10, threadId: 20 }
describe('execution ownership', () => {
  it('enforces unique IDs, one chat per window and one chat per thread', () => {
    const coordinator = new ExecutionCoordinator()
    const job = coordinator.begin(scope)
    expect(() => coordinator.begin(scope)).toThrow('already running')
    expect(() => coordinator.begin({ ...scope, requestId: 'two', threadId: 21 })).toThrow('already running')
    expect(() => coordinator.begin({ ...scope, requestId: 'two', ownerId: 2 })).toThrow('thread')
    const title = coordinator.begin({ ...scope, requestId: 'title', task: 'title' })
    expect(title.valid).toBe(true)
    job.finish()
    title.finish()
    expect(() => coordinator.begin(scope)).not.toThrow()
  })
  it('only lets the owning window stop work; stopping retains persistence permission', () => {
    const coordinator = new ExecutionCoordinator()
    const job = coordinator.begin(scope)
    expect(coordinator.stop('one', 2)).toBe(false)
    expect(job.signal.aborted).toBe(false)
    expect(coordinator.stop('one', 1)).toBe(true)
    expect(job.signal.aborted).toBe(true)
    expect(job.valid).toBe(true)
    job.finish()
    job.finish()
    expect(coordinator.stop('one')).toBe(false)
  })
  it.each(['thread', 'document', 'owner', 'chats'] as const)('invalidates %s without reviving work when IDs are reused', (kind) => {
    const coordinator = new ExecutionCoordinator()
    const job = coordinator.begin(scope)
    const title = coordinator.begin({ ...scope, requestId: 'title', task: 'title' })
    if (kind === 'thread') coordinator.invalidateThread(20)
    if (kind === 'document') coordinator.invalidateDocument(10)
    if (kind === 'owner') coordinator.invalidateOwner(1)
    if (kind === 'chats') coordinator.invalidateChats()
    expect(job.valid).toBe(false)
    expect(title.valid).toBe(false)
    expect(job.signal.aborted).toBe(true)
    const next = coordinator.begin({ ...scope, requestId: 'new' })
    expect(next.valid).toBe(true)
    expect(job.valid).toBe(false)
  })
  it('keeps independent document tagging alive during chat clears', () => {
    const coordinator = new ExecutionCoordinator()
    const tag = coordinator.begin({ requestId: 'tag', task: 'tagging', documentId: 10 })
    coordinator.invalidateChats()
    expect(tag.valid).toBe(true)
    coordinator.invalidateDocument(10)
    expect(tag.valid).toBe(false)
  })
  it('binds new threads and prevents moving a request between threads', () => {
    const coordinator = new ExecutionCoordinator()
    const job = coordinator.begin({ ...scope, threadId: undefined })
    job.bindThread(20)
    expect(job.scope.threadId).toBe(20)
    expect(() => job.bindThread(21)).toThrow('Cannot change')
    coordinator.invalidateThread(20)
    expect(job.valid).toBe(false)
  })
  it('shuts down all tasks and waits for their cleanup', async () => {
    const coordinator = new ExecutionCoordinator()
    const job = coordinator.begin(scope)
    let finished = false
    const shutdown = coordinator.shutdown().then(() => { finished = true })
    await Promise.resolve()
    expect(finished).toBe(false)
    expect(job.signal.aborted).toBe(true)
    expect(() => coordinator.begin({ ...scope, requestId: 'new' })).toThrow('shutting down')
    job.finish()
    await shutdown
    expect(finished).toBe(true)
  })
})
