"""create auth tables

Revision ID: 95f39bc57cd8
Revises:
Create Date: 2026-07-17 14:29:12.520852

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95f39bc57cd8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_identity_email"), "identity", ["email"], unique=True)
    op.create_table(
        "magiclinkcode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_magiclinkcode_identity_id"), "magiclinkcode", ["identity_id"], unique=False)
    op.create_index(op.f("ix_magiclinkcode_value"), "magiclinkcode", ["value"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_identity_id"), "user", ["identity_id"], unique=False)
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_identity_id"), "session", ["identity_id"], unique=False)
    op.create_index(op.f("ix_session_token"), "session", ["token"], unique=True)
    op.create_index(op.f("ix_session_user_id"), "session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_user_id"), table_name="session")
    op.drop_index(op.f("ix_session_token"), table_name="session")
    op.drop_index(op.f("ix_session_identity_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_user_identity_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_magiclinkcode_value"), table_name="magiclinkcode")
    op.drop_index(op.f("ix_magiclinkcode_identity_id"), table_name="magiclinkcode")
    op.drop_table("magiclinkcode")
    op.drop_index(op.f("ix_identity_email"), table_name="identity")
    op.drop_table("identity")
    # ### end Alembic commands ###
